story:
  base_instructions: "Please act as a creative content writer. strictly follow my commands, i dont need any extra information, headings or anything but the exact text."
  story_prompt: "write me a story of {1000} words in paragraphs, where each paragraph represents a plot. Theme of the story must be around these words: ['rainy','stormy','night','survival', 'Worldwar2','nerve wrenching','survival','pain', 'discipline']" 
  story_plot_images_prompt: "Please write me a Baseline Description for All Images strictly defining all the characters, landscape theme, weather theme, lighting theme, image style and more. Also prompts to generate each plot image. please write everything in a json format." 
joke_prompt: "write me a joke of {100} words. Theme of the story must be around these words: ['dark humour','adult jokes','humour','extreme funny']" 


'''
tips for images:
* Include Baseline Description for All Images.
Example: Please write me a prompt to generate all the plot images. Strictly use a Baseline Description for All Images strictly defining all the characters, landscape theme, weather theme, lighting theme, image style and more.

* Each prompt should be given separately prefixed with Baseline Description 
'''

'''
1: Pehle story fetch, phr images prompts separately
    step 1: write me a story in paragraphs, where each paragraph represents a plot.
    step 2: please write baseline description and all the image gen prompts as a json / dict.
'''


#Frame prompts:
""" 
Highlight 3 main keywords (named entities preffered separated by ,) from the given news:
Meta is reportedly working on AI-powered earphones equipped with cameras. Internally codenamed 'Camerabuds', the earphones will leverage AI capabilities for real-time object identification and foreign language translation. Meta's leadership sees AI-powered earphones as the next logical step in the evolution of wearable technology. It has partnered with Kansas-based electronics company Ear Micro to explore the possibilities of this emerging technology.

Generate 1 Square, Dark, Faded, Bluescale, Sci-fi, AI, Futuristic image, strictly having the following text/logo/girl: Reddit, OpenAI, Data API
"""


# Let's see

